services:
  wolfpack-bot:
    image: alex9158/ttbot:latest
    volumes:
      - "${TTBot_LOCAL_DIRECTORY}:/data/ttbot"
    environment:
      - TTBot_CONNECTION_STRING=${TTBot_CONNECTION_STRING}
      - TTBot_TOKEN=${TTBot_TOKEN}
      - TTBot_DATA_DIRECTORY=${TTBot_DATA_DIRECTORY}
      - TTBot_DISABLE_TWITTER=${TTBot_DISABLE_TWITTER}
      - TTBot_CONSUMER_KEY=${TTBot_CONSUMER_KEY}
      - TTBot_CONSUMER_SECRET=${TTBot_CONSUMER_SECRET}
      - TTBot_ACCESS_KEY=${TTBot_ACCESS_KEY}
      - TTBot_ACCESS_SECRET=${TTBot_ACCESS_SECRET}
  fileserver:
    image: emazzotta/simple-fileserver-docker
    volumes:
      - "${TTBot_LOCAL_DIRECTORY}/Standings:/app"
    ports:
      - 80:8000
