services:
  wolfpack-bot:
    build: .
    volumes:
      - "${TTBot_LOCAL_DIRECTORY}:/data/ttbot"
    environment:
      - TTBot_CONNECTION_STRING=${TTBot_CONNECTION_STRING}
      - TTBot_TOKEN=${TTBot_TOKEN}
      - TTBot_DATA_DIRECTORY=${TTBot_DATA_DIRECTORY}
      - TTBot_DISABLE_TWITTER=${TTBot_DISABLE_TWITTER}
  fileserver:
    image: emazzotta/simple-fileserver-docker
    volumes:
      - "${TTBot_LOCAL_DIRECTORY}/Standings:/app"
    ports:
      - 80:8000